apiVersion: v1
kind: ConfigMap
metadata:
  name: jumpstarter-controller
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: jumpstarter-controller
    {{ if .Values.global.timestamp }}
    deployment.timestamp: {{ .Values.global.timestamp | quote }}
    {{ end }}
data:
  authentication: {{- .Values.authenticationConfig | toYaml | indent 1 }}
  authorization: {{- .Values.authorizationConfig | toYaml | indent 1 }}
