
namespace: ""

grpc:
  hostname: ""
  ingress:
    enabled: false
    tls:
      enabled: false
      tlsSecret: ""
  
  route:
    enabled: false
    tls:
      enabled: true
  
  # NodePort service for grpc, useful for local development
  nodeport:
    enabled: false
    port: 30010

image: quay.io/jumpstarter-dev/jumpstarter-controller
tag: ""
imagePullPolicy: IfNotPresent

