
namespace: ""

grpc:
  hostname: ""
  ingress:
    enabled: true
    tls:
      enabled: false
      tlsSecret: ""
  
  route:
    enabled: false
    tls: true
  
image: quay.io/jumpstarter-dev/jumpstarter-controller
tag: ""
imagePullPolicy: IfNotPresent

