apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: jumpstarter-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: jumpstarter-client
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: jumpstarter-exporter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: jumpstarter-router
