## @section Global parameters
## @descriptionStart This section contains parameters common to all the
## components in the deployment.
## @descriptionEnd
##
## @param global.baseDomain Base domain to construct the FQDN for the service endpoints.
## @param global.namespace Namespace where the components will be deployed.
## @param global.storageClassName Storage class name for the PVCs.
## @param global.storageClassNameRWM Storage class name for multiple reader/writer PVCs.
## @param global.metrics.enabled Enable metrics exporting and service
## @param global.timestamp Timestamp to be used to trigger a new deployment, i.e. if you want pods to be restarted and pickup ":latest"

global:
  baseDomain: jumpstarter.my.domain.com
  namespace: jumpstarter-lab
  storageClassName: standard
  storageClassNameRWM: standard
  metrics:
      enabled: false
  timestamp: "" # can be used to timestamp deployments and make them reload

## @section Jumpstarter Controller parameters
## @descriptionStart This section contains parameters for the Jumpstarter Controller.
## @descriptionEnd
##
## @param jumpstarter-controller.enabled Enable the Jumpstarter Controller.

## @param jumpstarter-controller.image Image for the controller.
## @param jumpstarter-controller.tag Tag for the controller image.
## @param jumpstarter-controller.imagePullPolicy Image pull policy for the controller.

## @param jumpstarter-controller.namespace Namespace where the controller will be deployed, defaults to global.namespace.

## @param jumpstarter-controller.config.grpc.keepalive.minTime. The minimum amount of time a client should wait before sending a keepalive ping.
## @param jumpstarter-controller.config.grpc.keepalive.permitWithoutStream. Whether to allow keepalive pings even when there are no active streams(RPCs).

## @param jumpstarter-controller.config.authentication.internal.prefix. Prefix to add to the subject claim of the tokens issued by the builtin authenticator.
## @param jumpstarter-controller.config.authentication.jwt. External OIDC authentication, see https://kubernetes.io/docs/reference/access-authn-authz/authentication/#using-authentication-configuration for documentation

## @section Ingress And Route parameters
## @descriptionStart This section contains parameters for the Ingress and Route configurations.
## You can enable either the gRPC ingress or the OpenShift route but not both.
## @descriptionEnd
##
## @param jumpstarter-controller.grpc.hostname Hostname for the controller to use for the controller gRPC.
## @param jumpstarter-controller.grpc.routerHostname Hostname for the controller to use for the router gRPC.
##
## @param jumpstarter-controller.grpc.tls.mode Setup the TLS mode for endpoints, either "passthrough" or "reencrypt".
## @param jumpstarter-controller.grpc.tls.port Port to use for the gRPC endpoints ingress or route, this can be useful for ingress routers on non-standard ports.
## @param jumpstarter-controller.grpc.tls.controllerCertSecret Secret containing the TLS certificate/key for the gRPC endpoint.
## @param jumpstarter-controller.grpc.tls.routerCertSecret Secret containing the TLS certificate/key for the gRPC router endpoints.
##
## @param jumpstarter-controller.grpc.endpoint The endpoints are passed down to the services to
##                                           know where to announce the endpoints to the clients.
##
## @param jumpstarter-controller.grpc.routerEndpoint The endpoints are passed down to the services to
##                                                 know where to announce the endpoints to the clients.
##
## @param jumpstarter-controller.grpc.ingress.enabled Enable the gRPC ingress configuration.
##
## @param jumpstarter-controller.grpc.mode Mode to use for the gRPC endpoints, either route or ingress.



jumpstarter-controller:
    enabled: true

    image: quay.io/jumpstarter-dev/jumpstarter-controller
    tag: ""
    imagePullPolicy: IfNotPresent

    namespace: ""

    config:
      grpc:
        keepalive:
          # Safety: potentially makes server vulnerable to DDoS
          # https://grpc.io/docs/guides/keepalive/#how-configuring-keepalive-affects-a-call
          minTime: 3s
          permitWithoutStream: true
      authentication:
        internal:
          prefix: "internal:"
        # jwt:
        # - issuer:
        #     url: https://10.239.206.8:5556/dex
        #     audiences:
        #     - jumpstarter
        #     audienceMatchPolicy: MatchAny
        #     certificateAuthority: |
        #       -----BEGIN CERTIFICATE-----
        #       MIIB/DCCAYKgAwIBAgIIcpC2uS+SjEIwCgYIKoZIzj0EAwMwIDEeMBwGA1UEAxMV
        #       bWluaWNhIHJvb3QgY2EgNzI5MGI2MCAXDTI1MDIwMzE5MzMyNVoYDzIxMjUwMjAz
        #       MTkzMzI1WjAgMR4wHAYDVQQDExVtaW5pY2Egcm9vdCBjYSA3MjkwYjYwdjAQBgcq
        #       hkjOPQIBBgUrgQQAIgNiAAQzezKJ4My35HPeoJvvzTjhS2uJMBYrYfrs5csxZjiy
        #       q8ORrHM539XhWlA6sVZODhzcF2KL4mC9xKz/yIrsws+LKsIWNHGGmIPEKFYnHBGw
        #       VBGeARvhpzZP/9frJXAN/8ejgYYwgYMwDgYDVR0PAQH/BAQDAgKEMB0GA1UdJQQW
        #       MBQGCCsGAQUFBwMBBggrBgEFBQcDAjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1Ud
        #       DgQWBBSZRBCUuP3ta2xsfjnWIjvgvz4fojAfBgNVHSMEGDAWgBSZRBCUuP3ta2xs
        #       fjnWIjvgvz4fojAKBggqhkjOPQQDAwNoADBlAjADql5Ks5wh181iUa1ZBnx4XOVe
        #       l0l7I+mwlwJSPmkZHxruWZTx7gQU4tfDCr+UuzUCMQC2aDXRb17cphipK4gzbExv
        #       EDLExjhHAqMPrKDmT0jHIi7Bbos38/1tyZ/IoKjLnv0=
        #       -----END CERTIFICATE-----
        #   claimMappings:
        #     username:
        #       claim: "sub"
        #       prefix: ""

    grpc:
      hostname: ""
      routerHostname: ""

      endpoint: ""
      routerEndpoint: ""

      tls:
        mode: "passthrough"
        port: 443
        routerCertSecret: ""
        controllerCertSecret: ""

      mode: "route" # route or ingress
