global:
  baseDomain: jumpstarter.my.domain.com
  namespace: jumpstarter-lab
  storageClassName: standard
  storageClassNameRWM: standard
  metrics:
      enabled: false

jumpstarter-controller:
    enabled: true
    namespace: ""
    hostname: ""

    grpc:
      ingress:
        enabled: false
        tls:
          enabled: false
          tlsSecret: ""

      route:
        enabled: false
        tls:
          enabled: true

    image: quay.io/jumpstarter-dev/jumpstarter-controller
    tag: ""
    imagePullPolicy: IfNotPresent
