apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: jumpstarter-router
  name: controller-manager
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: jumpstarter-router
    app.kubernetes.io/managed-by: kustomize
  name: tokenholder
  namespace: {{ .Values.namespace }}
