apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: jumpstarter-controller
  name: jumpstarter-grpc
  namespace: {{ default .Release.Namespace .Values.namespace }}
spec:
  ports:
  - name: grpc
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    control-plane: controller-manager
