apiVersion: v1
kind: Secret
metadata:
  name: jumpstarter-controller-secret
  namespace: {{ default .Release.Namespace .Values.namespace }}
type: Opaque
data:
  {{- if .Values.controllerSecret }}
  key: {{ .Values.controllerSecret | b64enc }}
  {{- else -}}
  {{- if .Release.IsInstall }}
  key: {{ randAlphaNum 32 | b64enc }}
  {{ else }}
  key: {{ (lookup "v1" "Secret" (default .Release.Namespace .Values.namespace) "jumpstarter-controller-secret").data.key }}
  {{ end }}
  {{- end }}
