{{ if .Values.grpc.route.enabled }}
  {{ if .Values.grpc.ingress.enabled }}
    {{ required "grpc.ingress.enabled and grpc.route.enabled cannot be enabled at the same time" nil }}
  {{ end }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    external-exposed: "true"
    shard: external
  name: jumpstarter-router-route
  namespace: {{ default .Release.Namespace .Values.namespace }}
spec:
  {{ if .Values.grpc.routerHostname }}
  host: {{ .Values.grpc.routerHostname }}
  {{ else }}
  host: router.{{ .Values.global.baseDomain | required "a global.baseDomain or a grpc.routerHostname must be provided"}}
  {{ end }}
  port:
    targetPort: 8083
  {{ if .Values.grpc.tls.enabled }}
  tls:
    termination: edge
  {{ end }}
  to:
    kind: Service
    name: jumpstarter-router-grpc
    weight: 100
  wildcardPolicy: None
{{ end }}