name: End-to-end tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: jumpstarter-dev/jumpstarter-e2e
        with:
          controller-ref: ${{ github.ref }}
          jumpstarter-ref: main
