name: End-to-end tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: jumpstarter-dev/jumpstarter-e2e@main
        with:
          controller-ref: ${{ github.ref }}
          jumpstarter-ref: main
